/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_anpr_android_anpr */

#ifndef _Included_com_example_anpr_android_anpr
#define _Included_com_example_anpr_android_anpr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_anpr_android_anpr
 * Method:    CreatSVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_anpr_1android_anpr_CreatSVM
  (JNIEnv *, jobject);

/*
 * Class:     com_example_anpr_android_anpr
 * Method:    Recognize_result
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_anpr_1android_anpr_Recognize_1result
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
